version: "3.8"

services:
  user-service:
    build:
      context: ./backend/user-service
    ports:
      - "8001:8001"
    env_file:
      - ./backend/user-service/.env
    depends_on:
      - mongo_users

  post-service:
    build:
      context: ./backend/post-service
    ports:
      - "8002:8002"
    env_file:
      - ./backend/post-service/.env
    depends_on:
      - mongo_posts
      - minio

  notification-service:
    build:
      context: ./backend/notification-service
    ports:
      - "8003:8003"
    env_file:
      - ./backend/notification-service/.env
    depends_on:
      - mongo_notifications

  proxy:
    build:
      context: ./backend/proxy
    ports:
      - "80:80"
    depends_on:
      - user-service
      - post-service
      - notification-service

  mongo_users:
    image: mongo:4.4
    ports:
      - "27018:27017"
    volumes:
      - mongo-data-users:/data/db

  mongo_posts:
    image: mongo:4.4
    ports:
      - "27019:27017"
    volumes:
      - mongo-data-posts:/data/db

  mongo_notifications:
    image: mongo:4.4
    ports:
      - "27020:27017"
    volumes:
      - mongo-data-notifications:/data/db

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data

  # frontend:
  #   build:
  #     context: ./frontend
  #   command: server /data --console-address ":5173"
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - proxy

volumes:
  mongo-data-users:
  mongo-data-posts:
  mongo-data-notifications:
  minio-data:
